version: '2'
services:
    books-app:
        image: books
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://books-postgresql:5432/books
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9090:9090
    books-postgresql:
        extends:
            file: postgresql.yml
            service: books-postgresql
