version: '2'
services:
    books-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/books/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=books
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
